name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install zip
        run: |
          sudo apt update
          sudo apt install -y zip

      - name: Build
        run: deno task compile

      - name: Make Zip
        run: |
          cd build
          zip addon_compiler-x86_64-pc-windows-msvc.zip addon_compiler.exe
          zip addon_compiler-x86_64-unknown-linux-gnu.zip addon_compiler
          cd ..

      - name: Get Tag
        id: get-tag
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/addon_compiler-x86_64-pc-windows-msvc.zip
            build/addon_compiler-x86_64-unknown-linux-gnu.zip
          name: "Release ${{ steps.get-tag.outputs.VERSION }}"
          draft: true
